<?php
/**
 * Карточки countries-list: фолбэк-фото по slug.
 * Локальные снимки: /frontend/window/img/countries-list/{slug}.png
 * Используется если API countries-with-images не отдал картинку или URL относительный.
 */
return [
    'images' => [
        'turkey' => '/frontend/window/img/турция/turkey-stambul-22181.jpg',
        'egypt' => '/frontend/window/img/countries-list/egypt.png',
        'thailand' => '/frontend/window/img/countries-list/thailand.png',
        'uae' => '/frontend/window/img/countries-list/uae.png',
        'russia' => '/frontend/window/img/countries-list/russia.png',
        'china' => '/frontend/window/img/countries-list/china.png',
        'abkhazia' => '/frontend/window/img/countries-list/abkhazia.png',
        'armenia' => '/frontend/window/img/countries-list/armenia.png',
        'bahrain' => '/frontend/window/img/countries-list/bahrain.png',
        'cuba' => '/frontend/window/img/countries-list/cuba.png',
        'india' => '/frontend/window/img/countries-list/india.png',
        'indonesia' => '/frontend/window/img/countries-list/indonesia.png',
        'jordan' => '/frontend/window/img/countries-list/jordan.png',
        'mauritius' => '/frontend/window/img/countries-list/mauritius.png',
        'maldives' => '/frontend/window/img/countries-list/maldives.png',
        'montenegro' => '/frontend/window/img/countries-list/montenegro.png',
        'oman' => '/frontend/window/img/countries-list/oman.png',
        'philippines' => '/frontend/window/img/countries-list/philippines.png',
        'qatar' => '/frontend/window/img/countries-list/qatar.png',
        'seychelles' => '/frontend/window/img/countries-list/seychelles.png',
        'sri-lanka' => '/frontend/window/img/countries-list/sri-lanka.png',
        'tanzania' => '/frontend/window/img/countries-list/tanzania.png',
        'tunisia' => '/frontend/window/img/countries-list/tunisia.png',
        'venezuela' => '/frontend/window/img/countries-list/venezuela.png',
        'vietnam' => '/frontend/window/img/countries-list/vietnam.png',
        '_default' => 'https://images.unsplash.com/photo-1488646953014-85cb4e065289?auto=format&fit=crop&w=1400&q=82',
    ],
    'iso' => [
        'turkey' => 'TR',
        'egypt' => 'EG',
        'thailand' => 'TH',
        'uae' => 'AE',
        'russia' => 'RU',
        'china' => 'CN',
        'abkhazia' => 'AB',
        'armenia' => 'AM',
        'bahrain' => 'BH',
        'cuba' => 'CU',
        'india' => 'IN',
        'indonesia' => 'ID',
        'jordan' => 'JO',
        'mauritius' => 'MU',
        'maldives' => 'MV',
        'montenegro' => 'ME',
        'oman' => 'OM',
        'philippines' => 'PH',
        'qatar' => 'QA',
        'seychelles' => 'SC',
        'sri-lanka' => 'LK',
        'tanzania' => 'TZ',
        'tunisia' => 'TN',
        'venezuela' => 'VE',
        'vietnam' => 'VN',
    ],
];
