apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: app
  ports:
    - port: {{ .Values.app.service.port}}
      targetPort: {{ .Values.app.containerPort}}
      protocol: TCP
