apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  default.conf: |-
    server {
    listen 80;
    root /var/www/html;
    location ~ \.php$ {
      include fastcgi_params;
      fastcgi_pass app:9000;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
    location / {
      index index.php;
    }
    }
