server {
    #Server
    listen 80;
    #Root
    root /var/www/html;
    index index.php index.html;

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
    location / {
      try_files $uri $uri/ /index.php?$query_string;
    }
    #blocker
    location ^~ /data/ {
        deny all;
    }
    location ^~ /backend/config/ {
        deny all;
    }
    #Api
    location ~ ^/api/tourvisor-mobile/?$ {
        rewrite ^ /backend/api/tourvisor-mobile.php last;
    }
    location ~ ^/api/crm/?$ {
        rewrite ^ /backend/api/crm-mobile.php last;
    }
    #Feeds
    location = /feed-samara.yml {
        rewrite ^ /export/feed-by-departure.php?slug=samara last;
    }
    location = /feed-moscow.yml {
         rewrite ^ /export/feed-by-departure.php?slug=moscow last;
    }
    location = /feed.yml {
        rewrite ^ /export/yandex_rules_feed_yml.php last;
    }
}